title: WebLogic Android 博客
name: WebLogic Android 博客
description: Java, Android, React Native
author: BeanSoft
logo: https://avatars3.githubusercontent.com/u/11939450?v=4&s=100
github: https://github.com/codeasashu
about: React Native developer

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: aboutashu
#google_analytics:

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
