title: BeanSoft的 Java 架构随笔
name: BeanSoft的 Java 架构随笔
description: Java
author: BeanSoft
logo: https://avatars0.githubusercontent.com/u/11939450?v=4&s=100
github: https://github.com/beansoftapp/
about: Java

baseurl: ""
url: ""

allowsearch: true


share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
