title: 刘长炯的 Java 技术随笔
name: 刘长炯的 Java 技术随笔
description: Java, Android
author: BeanSoft
logo: https://avatars3.githubusercontent.com/u/11939450?v=4&s=100
github: https://github.com/beansoftapp/
about: Java, Android

baseurl: ""
url: ""

allowsearch: true


share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
